#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
-------------------------------------------------------------------------------
Welcome to the MEAN Stack!

MEAN is a boilerplate that provides a nice starting point for MongoDB, Node.js,
Express, and AngularJS based applications. It is designed to give you quick and
organized way to start developing of MEAN based web apps with useful modules like
mongoose and passport pre-bundled and configured. We mainly try to take care of
the connection points between existing popular frameworks and solve common
integration problems.

MEAN has been installed via "docker-compose"

To get started with the sample app, go to "/opt/mean" and run "docker-compose up"
You can then view the sample app at http://${myip}:3000

The "ufw" firewall is enabled. All ports except for 22, 80, 443, and 3000
are BLOCKED.

-------------------------------------------------------------------------------
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
